### ISSUE TITLE
Missing Requirements in version 2.13.0.42

### ISSUE THREAD

**Issue by cybersonic** [lucee/extension-mongodb#2]
I have installed the mongoDB extension via the Application page in the Lucee admin on Lucee 	Lucee 5.0.0.178-BETA and when system starts I get: 

`Unresolved constraint in bundle mongodb.extension [83]: Unable to resolve 83.0: missing requirement [83.0] osgi.wiring.bundle; (&(osgi.wiring.bundle=org.mongodb.mongo-java-driver)(bundle-version>=2.13.0.RELEASE)) [caused by: Unable to resolve 84.0: missing requirement [84.0] osgi.wiring.package; (osgi.wiring.package=javax.security.sasl)]`

any ideas?

**Comment by andrew-dixon** [comment]
@cybersonic Have you tried the latest snapshot, 184, I think I saw Micha saying he had done something with MongoDB recently. No idea however if it fixes this issue.

**Comment by cybersonic** [comment]
Where can I download this? I am currently forking and building it from scratch…

**Comment by andrew-dixon** [comment]
@cybersonic http://preview.lucee.org/download/?type=snapshots

**Comment by cybersonic** [comment]
I spent a long time looking for this url maybe would be an idea to add it to the lucee.org <http://lucee.org/> site?
(under downloads)

**Comment by andrew-dixon** [comment]
@cybersonic Yeah, good point, I'll get it sorted out, however I just noticed the snapshots can be downloaded from the download page on lucee.org as well, they are at the bottom of the page: http://lucee.org/downloads.html

**Comment by sjdaniels** [comment]
I believe the fix was introduced somewhere in the 181 snapshot range. Let me know how it goes. Mark, are you using the extension for cache or just normal MongoDB operations? I could use someone familiar with the cache provider to help out with an issue I'm seeing trying to write some tests.

**Comment by cybersonic** [comment]
I got it working using the snapshot as @andrew-dixon suggested. 

Do you have a an issue related to the cache provider? I am not using the cache provider for the current project though.

**Comment by sjdaniels** [comment]
Yes, cachePut throws an exception when trying to use an array, struct, or date as the value (numerics and strings work). I do not use the cache provider at all, I was just trying to make sure the test suite covered the cache provider as well. I've merged the tests I created if you want to have a look, but I'm not particularly qualified (or motivated) to fix this. :)
