### ISSUE TITLE
$set $push...

### ISSUE THREAD

**Issue by matthinc** [lucee/extension-mongodb#23]
Hi,

is this somehow possible:
`db["user"].update(
	{ "_id": user },
	{
	    "lists": {
		"$set": newObject
	     }
	},
	false
);
`
I always get the error message
`"Invalid BSON field name $set"`

Same for $push...

It works just fine in node.js

Thank you

**Comment by sjdaniels** [comment]
I think you have the update syntax wrong. Should be:

`db["user"].update( { "_id": user }, { "$set": { "lists": newObject } }, false );`

**Comment by matthinc** [comment]
Wow - thank you for the quick repsonse. But this sadly doesn't work either.
Now I get

`"Timed out after 30000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=REPLICA_SET, servers=[{address=development-shard-00-02-kajij.mongodb.net:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketReadException: Prematurely reached end of stream}}, {address=development-shard-00-01-kajij.mongodb.net:27017, type=REPLICA_SET_SECONDARY, roundTripTime=88,2 ms, state=CONNECTED}, {address=development-shard-00-00-kajij.mongodb.net:27017, type=REPLICA_SET_SECONDARY, roundTripTime=89,2 ms, state=CONNECTED}]"`

**Comment by sjdaniels** [comment]
That's a straight ahead connection error. Your application server can not talk to your cluster. Looks like you are hosting on Atlas or MongoDB Cloud? Make sure your firewall settings allow access from your Lucee server.

**Comment by matthinc** [comment]
Oh yes - server is down. No problem with Lucee, sorry.
